[package]
name = "limestreamer"
version = "0.1.0"
authors = ["Limespy"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half = "2.4.0"
rand = "0.8.5"
